name: Trigger-All-Workflows  # 主要工作流的名称

on:
  workflow_dispatch:  # 手动触发：通过 GitHub UI 来触发
  schedule:

jobs:
    Athena-ImmortalWrt:
      uses: ./.github/workflows/Athena-ImmortalWrt.yml

    All-Clean:
      uses: ./.github/workflows/All-Clean.yml
